export const ALL_SUBJECTS = [
  'Mathematik',
  'Deutsch',
  'Englisch',
  'Französisch',
  'Spanisch',
  'Latein',
  'Physik',
  'Chemie',
  'Biologie',
  'Geschichte',
  'Geographie',
  'Politik',
  'Wirtschaft',
  'Informatik',
  'Kunst',
  'Musik',
  'Sport',
  'Religion',
  'Ethik',
  'Philosophie',
  'Sachunterricht',
  'Technik',
  'Hauswirtschaft',
  'Darstellendes Spiel',
] as const;
